/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "HiReSamHeader.h"
#include "HiReSamAudioProcessor.h"
#include "Spectroscope.h"
#include "PitchDetectorComponent.h"


//==============================================================================
/**
*/
class HiReSamAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    HiReSamAudioProcessorEditor (HiReSamAudioProcessor* ownerFilter);
    ~HiReSamAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void resized();
    
    Spectroscope spectroscope;
    PitchDetectorComponent pitchDetector;
    
private:
    TimeSliceThread renderThread;
};


#endif  // PLUGINEDITOR_H_INCLUDED
