/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "HiReSamHeader.h"
#include "HiReMeAudioProcessor.h"


//==============================================================================
/**
*/
class HiReMeAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    HiReMeAudioProcessorEditor (HiReMeAudioProcessor* ownerFilter);
    ~HiReMeAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void resized();
    
    Spectroscope spectroscope;
    
private:
    TimeSliceThread renderThread;
};


#endif  // PLUGINEDITOR_H_INCLUDED
